version: '3.5'

services:
  lobbyserver:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "BUKKIT"
      ONLINE_MODE: "FALSE"
  mainserver:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MEMORY: "3G"
      ONLINE_MODE: "FALSE"
    ports:
      - 25566:25565
  bungeecord:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
    ports:
      - 25565:25577
    volumes:
      - ./config.yml:/config/config.yml
